Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "centos-59"
  c.vm.box_url = "file:///Users/501759691/VirtualBox VMs/CentOS-6.6-x86_64-v20150426.box"
  c.vm.hostname = "default-centos-60"
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8000})
  c.vm.network(:forwarded_port, {:guest=>8080, :host=>7000})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
